// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sla.proto
#ifndef GRPC_sla_2eproto__INCLUDED
#define GRPC_sla_2eproto__INCLUDED

#include "sla.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace sla {

class tpu final {
 public:
  static constexpr char const* service_full_name() {
    return "sla.tpu";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status _init(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::sla::tpu_conf_res* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_conf_res>> Async_init(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_conf_res>>(Async_initRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_conf_res>> PrepareAsync_init(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_conf_res>>(PrepareAsync_initRaw(context, request, cq));
    }
    virtual ::grpc::Status _invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req& request, ::sla::tpu_calc_res* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_calc_res>> Async_invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_calc_res>>(Async_invokeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_calc_res>> PrepareAsync_invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_calc_res>>(PrepareAsync_invokeRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void _init(::grpc::ClientContext* context, const ::sla::tpu_conf_req* request, ::sla::tpu_conf_res* response, std::function<void(::grpc::Status)>) = 0;
      virtual void _init(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_conf_res* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void _init(::grpc::ClientContext* context, const ::sla::tpu_conf_req* request, ::sla::tpu_conf_res* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void _init(::grpc::ClientContext* context, const ::sla::tpu_conf_req* request, ::sla::tpu_conf_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void _init(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_conf_res* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void _init(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_conf_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void _invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req* request, ::sla::tpu_calc_res* response, std::function<void(::grpc::Status)>) = 0;
      virtual void _invoke(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_calc_res* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void _invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req* request, ::sla::tpu_calc_res* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void _invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req* request, ::sla::tpu_calc_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void _invoke(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_calc_res* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void _invoke(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_calc_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_conf_res>* Async_initRaw(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_conf_res>* PrepareAsync_initRaw(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_calc_res>* Async_invokeRaw(::grpc::ClientContext* context, const ::sla::tpu_calc_req& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sla::tpu_calc_res>* PrepareAsync_invokeRaw(::grpc::ClientContext* context, const ::sla::tpu_calc_req& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status _init(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::sla::tpu_conf_res* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sla::tpu_conf_res>> Async_init(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sla::tpu_conf_res>>(Async_initRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sla::tpu_conf_res>> PrepareAsync_init(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sla::tpu_conf_res>>(PrepareAsync_initRaw(context, request, cq));
    }
    ::grpc::Status _invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req& request, ::sla::tpu_calc_res* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sla::tpu_calc_res>> Async_invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sla::tpu_calc_res>>(Async_invokeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sla::tpu_calc_res>> PrepareAsync_invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sla::tpu_calc_res>>(PrepareAsync_invokeRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void _init(::grpc::ClientContext* context, const ::sla::tpu_conf_req* request, ::sla::tpu_conf_res* response, std::function<void(::grpc::Status)>) override;
      void _init(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_conf_res* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void _init(::grpc::ClientContext* context, const ::sla::tpu_conf_req* request, ::sla::tpu_conf_res* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void _init(::grpc::ClientContext* context, const ::sla::tpu_conf_req* request, ::sla::tpu_conf_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void _init(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_conf_res* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void _init(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_conf_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void _invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req* request, ::sla::tpu_calc_res* response, std::function<void(::grpc::Status)>) override;
      void _invoke(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_calc_res* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void _invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req* request, ::sla::tpu_calc_res* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void _invoke(::grpc::ClientContext* context, const ::sla::tpu_calc_req* request, ::sla::tpu_calc_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void _invoke(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_calc_res* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void _invoke(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_calc_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sla::tpu_conf_res>* Async_initRaw(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sla::tpu_conf_res>* PrepareAsync_initRaw(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sla::tpu_calc_res>* Async_invokeRaw(::grpc::ClientContext* context, const ::sla::tpu_calc_req& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sla::tpu_calc_res>* PrepareAsync_invokeRaw(::grpc::ClientContext* context, const ::sla::tpu_calc_req& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod__init_;
    const ::grpc::internal::RpcMethod rpcmethod__invoke_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status _init(::grpc::ServerContext* context, const ::sla::tpu_conf_req* request, ::sla::tpu_conf_res* response);
    virtual ::grpc::Status _invoke(::grpc::ServerContext* context, const ::sla::tpu_calc_req* request, ::sla::tpu_calc_res* response);
  };
  template <class BaseClass>
  class WithAsyncMethod__init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod__init() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod__init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _init(::grpc::ServerContext* /*context*/, const ::sla::tpu_conf_req* /*request*/, ::sla::tpu_conf_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Request_init(::grpc::ServerContext* context, ::sla::tpu_conf_req* request, ::grpc::ServerAsyncResponseWriter< ::sla::tpu_conf_res>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod__invoke : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod__invoke() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod__invoke() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _invoke(::grpc::ServerContext* /*context*/, const ::sla::tpu_calc_req* /*request*/, ::sla::tpu_calc_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Request_invoke(::grpc::ServerContext* context, ::sla::tpu_calc_req* request, ::grpc::ServerAsyncResponseWriter< ::sla::tpu_calc_res>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod__init<WithAsyncMethod__invoke<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod__init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod__init() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::sla::tpu_conf_req, ::sla::tpu_conf_res>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::sla::tpu_conf_req* request, ::sla::tpu_conf_res* response) { return this->_init(context, request, response); }));}
    void SetMessageAllocatorFor__init(
        ::grpc::experimental::MessageAllocator< ::sla::tpu_conf_req, ::sla::tpu_conf_res>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::sla::tpu_conf_req, ::sla::tpu_conf_res>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod__init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _init(::grpc::ServerContext* /*context*/, const ::sla::tpu_conf_req* /*request*/, ::sla::tpu_conf_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* _init(
      ::grpc::CallbackServerContext* /*context*/, const ::sla::tpu_conf_req* /*request*/, ::sla::tpu_conf_res* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* _init(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::sla::tpu_conf_req* /*request*/, ::sla::tpu_conf_res* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod__invoke : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod__invoke() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::sla::tpu_calc_req, ::sla::tpu_calc_res>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::sla::tpu_calc_req* request, ::sla::tpu_calc_res* response) { return this->_invoke(context, request, response); }));}
    void SetMessageAllocatorFor__invoke(
        ::grpc::experimental::MessageAllocator< ::sla::tpu_calc_req, ::sla::tpu_calc_res>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::sla::tpu_calc_req, ::sla::tpu_calc_res>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod__invoke() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _invoke(::grpc::ServerContext* /*context*/, const ::sla::tpu_calc_req* /*request*/, ::sla::tpu_calc_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* _invoke(
      ::grpc::CallbackServerContext* /*context*/, const ::sla::tpu_calc_req* /*request*/, ::sla::tpu_calc_res* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* _invoke(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::sla::tpu_calc_req* /*request*/, ::sla::tpu_calc_res* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod__init<ExperimentalWithCallbackMethod__invoke<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod__init<ExperimentalWithCallbackMethod__invoke<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod__init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod__init() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod__init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _init(::grpc::ServerContext* /*context*/, const ::sla::tpu_conf_req* /*request*/, ::sla::tpu_conf_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod__invoke : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod__invoke() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod__invoke() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _invoke(::grpc::ServerContext* /*context*/, const ::sla::tpu_calc_req* /*request*/, ::sla::tpu_calc_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod__init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod__init() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod__init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _init(::grpc::ServerContext* /*context*/, const ::sla::tpu_conf_req* /*request*/, ::sla::tpu_conf_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Request_init(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod__invoke : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod__invoke() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod__invoke() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _invoke(::grpc::ServerContext* /*context*/, const ::sla::tpu_calc_req* /*request*/, ::sla::tpu_calc_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Request_invoke(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod__init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod__init() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->_init(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod__init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _init(::grpc::ServerContext* /*context*/, const ::sla::tpu_conf_req* /*request*/, ::sla::tpu_conf_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* _init(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* _init(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod__invoke : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod__invoke() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->_invoke(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod__invoke() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status _invoke(::grpc::ServerContext* /*context*/, const ::sla::tpu_calc_req* /*request*/, ::sla::tpu_calc_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* _invoke(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* _invoke(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod__init : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod__init() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::sla::tpu_conf_req, ::sla::tpu_conf_res>(std::bind(&WithStreamedUnaryMethod__init<BaseClass>::Streamed_init, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod__init() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status _init(::grpc::ServerContext* /*context*/, const ::sla::tpu_conf_req* /*request*/, ::sla::tpu_conf_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamed_init(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sla::tpu_conf_req,::sla::tpu_conf_res>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod__invoke : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod__invoke() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::sla::tpu_calc_req, ::sla::tpu_calc_res>(std::bind(&WithStreamedUnaryMethod__invoke<BaseClass>::Streamed_invoke, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod__invoke() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status _invoke(::grpc::ServerContext* /*context*/, const ::sla::tpu_calc_req* /*request*/, ::sla::tpu_calc_res* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamed_invoke(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sla::tpu_calc_req,::sla::tpu_calc_res>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod__init<WithStreamedUnaryMethod__invoke<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod__init<WithStreamedUnaryMethod__invoke<Service > > StreamedService;
};

}  // namespace sla


#endif  // GRPC_sla_2eproto__INCLUDED
