// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sla.proto

#include "sla.pb.h"
#include "sla.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace sla {

static const char* tpu_method_names[] = {
  "/sla.tpu/_init",
  "/sla.tpu/_ref_phase_compute",
  "/sla.tpu/_depth_compute",
};

std::unique_ptr< tpu::Stub> tpu::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< tpu::Stub> stub(new tpu::Stub(channel));
  return stub;
}

tpu::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod__init_(tpu_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod__ref_phase_compute_(tpu_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod__depth_compute_(tpu_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status tpu::Stub::_init(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::sla::tpu_status_res* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod__init_, context, request, response);
}

void tpu::Stub::experimental_async::_init(::grpc::ClientContext* context, const ::sla::tpu_conf_req* request, ::sla::tpu_status_res* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod__init_, context, request, response, std::move(f));
}

void tpu::Stub::experimental_async::_init(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_status_res* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod__init_, context, request, response, std::move(f));
}

void tpu::Stub::experimental_async::_init(::grpc::ClientContext* context, const ::sla::tpu_conf_req* request, ::sla::tpu_status_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod__init_, context, request, response, reactor);
}

void tpu::Stub::experimental_async::_init(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_status_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod__init_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sla::tpu_status_res>* tpu::Stub::Async_initRaw(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::sla::tpu_status_res>::Create(channel_.get(), cq, rpcmethod__init_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::sla::tpu_status_res>* tpu::Stub::PrepareAsync_initRaw(::grpc::ClientContext* context, const ::sla::tpu_conf_req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::sla::tpu_status_res>::Create(channel_.get(), cq, rpcmethod__init_, context, request, false);
}

::grpc::Status tpu::Stub::_ref_phase_compute(::grpc::ClientContext* context, const ::sla::tpu_env_req& request, ::sla::tpu_status_res* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod__ref_phase_compute_, context, request, response);
}

void tpu::Stub::experimental_async::_ref_phase_compute(::grpc::ClientContext* context, const ::sla::tpu_env_req* request, ::sla::tpu_status_res* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod__ref_phase_compute_, context, request, response, std::move(f));
}

void tpu::Stub::experimental_async::_ref_phase_compute(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_status_res* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod__ref_phase_compute_, context, request, response, std::move(f));
}

void tpu::Stub::experimental_async::_ref_phase_compute(::grpc::ClientContext* context, const ::sla::tpu_env_req* request, ::sla::tpu_status_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod__ref_phase_compute_, context, request, response, reactor);
}

void tpu::Stub::experimental_async::_ref_phase_compute(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::tpu_status_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod__ref_phase_compute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sla::tpu_status_res>* tpu::Stub::Async_ref_phase_computeRaw(::grpc::ClientContext* context, const ::sla::tpu_env_req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::sla::tpu_status_res>::Create(channel_.get(), cq, rpcmethod__ref_phase_compute_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::sla::tpu_status_res>* tpu::Stub::PrepareAsync_ref_phase_computeRaw(::grpc::ClientContext* context, const ::sla::tpu_env_req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::sla::tpu_status_res>::Create(channel_.get(), cq, rpcmethod__ref_phase_compute_, context, request, false);
}

::grpc::Status tpu::Stub::_depth_compute(::grpc::ClientContext* context, const ::sla::tpu_env_req& request, ::sla::depth_env_res* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod__depth_compute_, context, request, response);
}

void tpu::Stub::experimental_async::_depth_compute(::grpc::ClientContext* context, const ::sla::tpu_env_req* request, ::sla::depth_env_res* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod__depth_compute_, context, request, response, std::move(f));
}

void tpu::Stub::experimental_async::_depth_compute(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::depth_env_res* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod__depth_compute_, context, request, response, std::move(f));
}

void tpu::Stub::experimental_async::_depth_compute(::grpc::ClientContext* context, const ::sla::tpu_env_req* request, ::sla::depth_env_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod__depth_compute_, context, request, response, reactor);
}

void tpu::Stub::experimental_async::_depth_compute(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sla::depth_env_res* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod__depth_compute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sla::depth_env_res>* tpu::Stub::Async_depth_computeRaw(::grpc::ClientContext* context, const ::sla::tpu_env_req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::sla::depth_env_res>::Create(channel_.get(), cq, rpcmethod__depth_compute_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::sla::depth_env_res>* tpu::Stub::PrepareAsync_depth_computeRaw(::grpc::ClientContext* context, const ::sla::tpu_env_req& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::sla::depth_env_res>::Create(channel_.get(), cq, rpcmethod__depth_compute_, context, request, false);
}

tpu::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      tpu_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< tpu::Service, ::sla::tpu_conf_req, ::sla::tpu_status_res>(
          std::mem_fn(&tpu::Service::_init), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      tpu_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< tpu::Service, ::sla::tpu_env_req, ::sla::tpu_status_res>(
          std::mem_fn(&tpu::Service::_ref_phase_compute), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      tpu_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< tpu::Service, ::sla::tpu_env_req, ::sla::depth_env_res>(
          std::mem_fn(&tpu::Service::_depth_compute), this)));
}

tpu::Service::~Service() {
}

::grpc::Status tpu::Service::_init(::grpc::ServerContext* context, const ::sla::tpu_conf_req* request, ::sla::tpu_status_res* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status tpu::Service::_ref_phase_compute(::grpc::ServerContext* context, const ::sla::tpu_env_req* request, ::sla::tpu_status_res* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status tpu::Service::_depth_compute(::grpc::ServerContext* context, const ::sla::tpu_env_req* request, ::sla::depth_env_res* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sla

