# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sla_pb2 as sla__pb2


class phase_unwrapStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.tpu_invoke = channel.unary_unary(
        '/sla.phase_unwrap/tpu_invoke',
        request_serializer=sla__pb2.tpu_req.SerializeToString,
        response_deserializer=sla__pb2.tpu_res.FromString,
        )


class phase_unwrapServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def tpu_invoke(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_phase_unwrapServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'tpu_invoke': grpc.unary_unary_rpc_method_handler(
          servicer.tpu_invoke,
          request_deserializer=sla__pb2.tpu_req.FromString,
          response_serializer=sla__pb2.tpu_res.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sla.phase_unwrap', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
