# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sla.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sla.proto',
  package='sla',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tsla.proto\x12\x03sla\"Y\n\x07tpu_req\x12\x12\n\nurl_ref_lf\x18\x01 \x01(\t\x12\x12\n\nurl_ref_hf\x18\x02 \x01(\t\x12\x12\n\nurl_obj_lf\x18\x03 \x01(\t\x12\x12\n\nurl_obj_hf\x18\x04 \x01(\t\"#\n\x07tpu_res\x12\x18\n\x10url_unwrap_phase\x18\x01 \x01(\t2:\n\x0cphase_unwrap\x12*\n\ntpu_invoke\x12\x0c.sla.tpu_req\x1a\x0c.sla.tpu_res\"\x00\x62\x06proto3'
)




_TPU_REQ = _descriptor.Descriptor(
  name='tpu_req',
  full_name='sla.tpu_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url_ref_lf', full_name='sla.tpu_req.url_ref_lf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url_ref_hf', full_name='sla.tpu_req.url_ref_hf', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url_obj_lf', full_name='sla.tpu_req.url_obj_lf', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url_obj_hf', full_name='sla.tpu_req.url_obj_hf', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=107,
)


_TPU_RES = _descriptor.Descriptor(
  name='tpu_res',
  full_name='sla.tpu_res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url_unwrap_phase', full_name='sla.tpu_res.url_unwrap_phase', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['tpu_req'] = _TPU_REQ
DESCRIPTOR.message_types_by_name['tpu_res'] = _TPU_RES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

tpu_req = _reflection.GeneratedProtocolMessageType('tpu_req', (_message.Message,), {
  'DESCRIPTOR' : _TPU_REQ,
  '__module__' : 'sla_pb2'
  # @@protoc_insertion_point(class_scope:sla.tpu_req)
  })
_sym_db.RegisterMessage(tpu_req)

tpu_res = _reflection.GeneratedProtocolMessageType('tpu_res', (_message.Message,), {
  'DESCRIPTOR' : _TPU_RES,
  '__module__' : 'sla_pb2'
  # @@protoc_insertion_point(class_scope:sla.tpu_res)
  })
_sym_db.RegisterMessage(tpu_res)



_PHASE_UNWRAP = _descriptor.ServiceDescriptor(
  name='phase_unwrap',
  full_name='sla.phase_unwrap',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=146,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='tpu_invoke',
    full_name='sla.phase_unwrap.tpu_invoke',
    index=0,
    containing_service=None,
    input_type=_TPU_REQ,
    output_type=_TPU_RES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PHASE_UNWRAP)

DESCRIPTOR.services_by_name['phase_unwrap'] = _PHASE_UNWRAP

# @@protoc_insertion_point(module_scope)
