# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sla_pb2 as sla__pb2


class tpuStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self._init = channel.unary_unary(
        '/sla.tpu/_init',
        request_serializer=sla__pb2.tpu_conf_req.SerializeToString,
        response_deserializer=sla__pb2.tpu_status_res.FromString,
        )
    self._ref_phase_compute = channel.unary_unary(
        '/sla.tpu/_ref_phase_compute',
        request_serializer=sla__pb2.tpu_env_req.SerializeToString,
        response_deserializer=sla__pb2.tpu_status_res.FromString,
        )
    self._depth_compute = channel.unary_unary(
        '/sla.tpu/_depth_compute',
        request_serializer=sla__pb2.tpu_env_req.SerializeToString,
        response_deserializer=sla__pb2.depth_env_res.FromString,
        )


class tpuServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def _init(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def _ref_phase_compute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def _depth_compute(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_tpuServicer_to_server(servicer, server):
  rpc_method_handlers = {
      '_init': grpc.unary_unary_rpc_method_handler(
          servicer._init,
          request_deserializer=sla__pb2.tpu_conf_req.FromString,
          response_serializer=sla__pb2.tpu_status_res.SerializeToString,
      ),
      '_ref_phase_compute': grpc.unary_unary_rpc_method_handler(
          servicer._ref_phase_compute,
          request_deserializer=sla__pb2.tpu_env_req.FromString,
          response_serializer=sla__pb2.tpu_status_res.SerializeToString,
      ),
      '_depth_compute': grpc.unary_unary_rpc_method_handler(
          servicer._depth_compute,
          request_deserializer=sla__pb2.tpu_env_req.FromString,
          response_serializer=sla__pb2.depth_env_res.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sla.tpu', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
